<?php

use App\driver as driver;
use Illuminate\Database\Seeder;

class DriverSeeder extends Seeder{
	public function run(){
		driver::truncate();
		driver::create(["fullname_th"=>"อุทัย  กันหาลีลา","fullname_en"=>"-","nickname"=>"D.อุทัย","tel"=>"089-557 7695","line"=>"","license_no"=>"นง2663 ชม","note"=>"รถออฟฟิศ มีบัตรผ่านกองบิน","seat"=>"9","is_provincial"=>"1","is_wing41"=>"1","is_staff"=>"1","is_priority"=>"1","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"ชนทัช  ชีพพึ่งวนา","fullname_en"=>"-","nickname"=>"D.เหย่ง","tel"=>"085-623 6416","line"=>"","license_no"=>"นง4202 ชม","note"=>"รถออฟฟิศ มีบัตรผ่านกองบิน","seat"=>"9","is_provincial"=>"1","is_wing41"=>"1","is_staff"=>"1","is_priority"=>"1","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"กิตติคุณ  ขุมคำ","fullname_en"=>"-","nickname"=>"D.เมย์","tel"=>"084-986 6510","line"=>"","license_no"=>"นค7811 ชม","note"=>"รถออฟฟิศ มีบัตรผ่านกองบิน","seat"=>"9","is_provincial"=>"1","is_wing41"=>"1","is_staff"=>"1","is_priority"=>"1","is_sticker"=>"1"]);
		driver::create(["fullname_th"=>"สายันต์  เมืองแก้ว","fullname_en"=>"-","nickname"=>"D.สายันต์","tel"=>"085-716 0009","line"=>"","license_no"=>"","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"1","is_priority"=>"1","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"สุพจน์  สีดา","fullname_en"=>"-","nickname"=>"V.พจน์","tel"=>"081-180 6969","line"=>"","license_no"=>"36-0023 ชม","note"=>"ทุกอย่างดี  ไม่เกี่ยงงาน","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"2","is_sticker"=>"1"]);
		driver::create(["fullname_th"=>"ศักดา  ปันวารี","fullname_en"=>"-","nickname"=>"V.แม็กซ์","tel"=>"088-411 5298","line"=>"","license_no"=>"36-0206 ชม","note"=>"ขับรถดี  อัธยาศัยดี","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"2","is_sticker"=>"1"]);
		driver::create(["fullname_th"=>"ประยุทธ  กันดีโรจน์","fullname_en"=>"-","nickname"=>"V.ประยุทธ","tel"=>"089-557 2322","line"=>"","license_no"=>"30-2811 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"สมบัติ  ทรายแสน","fullname_en"=>"-","nickname"=>"V.สมบัติ","tel"=>"081-706 2181","line"=>"","license_no"=>"30-2611 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"วิชาญ  ธรรมขันธ์","fullname_en"=>"-","nickname"=>"V.เหน่ง","tel"=>"087-578 0585","line"=>"","license_no"=>"นค8875 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"กำธร  ชุดินทราศรี","fullname_en"=>"-","nickname"=>"V.เก่ง","tel"=>"083-105 0262","line"=>"","license_no"=>"30-2891 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"อินพัตร  พรมยวง","fullname_en"=>"-","nickname"=>"V.หลาน","tel"=>"084-610 1442","line"=>"","license_no"=>"นค8730 ชม","note"=>"พูดมาก  บริการดี  ไม่เกี่ยงงาน","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"ราษี  ไร่เรือง","fullname_en"=>"-","nickname"=>"V.แอร์","tel"=>"087-469 6589","line"=>"","license_no"=>"นข3615 ชร","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"อาทิตย์  ฝนตก","fullname_en"=>"-","nickname"=>"V.อาทิตย์","tel"=>"089-557 5940","line"=>"","license_no"=>"นง1685 ชม","note"=>"สูบบุหรี่  มีกลิ่นแรง","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"พงษ์เทพ  ชุ่มใจ","fullname_en"=>"-","nickname"=>"V.ปอย","tel"=>"089-838 3717","line"=>"","license_no"=>"30-3026 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"","fullname_en"=>"-","nickname"=>"V.วี","tel"=>"091-272 5198","line"=>"","license_no"=>"","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"","fullname_en"=>"-","nickname"=>"V.บัญชา","tel"=>"090-282 4244","line"=>"","license_no"=>"","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"วันเฉลิม  ชอบยิ้มหอม","fullname_en"=>"-","nickname"=>"V.ตี๋ (บัญชา)","tel"=>"081-998 5772","line"=>"","license_no"=>"30-2335 ชม","note"=>"บ้านอยู่ในเมือง  เรียกใช้ได้เสมอ","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"สุมินทร์  ทะบุญ","fullname_en"=>"-","nickname"=>"V.สุมินทร์ (บัญชา)","tel"=>"089-838 4549","line"=>"","license_no"=>"นง6044 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"สัมฤทธิ์  วรรณจักร์","fullname_en"=>"-","nickname"=>"V.อเนก (บัญชา)","tel"=>"089-555 5877","line"=>"","license_no"=>"ฮภ7534 กทม","note"=>"บริการดี  อัธยาศัยดี","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"","fullname_en"=>"-","nickname"=>"V.จรัญ (บัญชา)","tel"=>"081-960 6307","line"=>"","license_no"=>"","note"=>"รถ  14  ที่นั่ง","seat"=>"14","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"","fullname_en"=>"-","nickname"=>"V.จำเนียร (บัญชา)","tel"=>"084-549 4756","line"=>"","license_no"=>"","note"=>"รถ  14  ที่นั่ง","seat"=>"14","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"","fullname_en"=>"-","nickname"=>"V.เอก","tel"=>"","line"=>"","license_no"=>"","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"","fullname_en"=>"-","nickname"=>"V.ใหญ่ (K.เอก)","tel"=>"081-352 0047","line"=>"","license_no"=>"","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"เกียรติศักดิ์  คำแปง","fullname_en"=>"-","nickname"=>"V.เก่ียรติ (K.เอก)","tel"=>"099-449 2062","line"=>"","license_no"=>"30-3229 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"ชูนาท  ปันแปง","fullname_en"=>"-","nickname"=>"V.นาท (Arm)","tel"=>"083-475 7795","line"=>"","license_no"=>"นข3182 ลพ","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"อเนก  กันธา","fullname_en"=>"-","nickname"=>"V.ใหญ่ (Arm)","tel"=>"082-890 3575","line"=>"","license_no"=>"36-0078 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"กุลนันท์  ทับทิม","fullname_en"=>"-","nickname"=>"V.เลย์ (Max)","tel"=>"085-864 8262","line"=>"","license_no"=>"36-0325 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"ตะวัน  บุญแฝผล","fullname_en"=>"-","nickname"=>"V.โม่ง (Max)","tel"=>"097-996 0824","line"=>"","license_no"=>"","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"จักรกริช  ทับทิม","fullname_en"=>"-","nickname"=>"V.กฤษ (Max)","tel"=>"093-140 0619","line"=>"","license_no"=>"นง7734 ชม","note"=>"พูดมาก  บริการดี  ไม่เกี่ยงงาน  เบาะใหญ่  กว้าง","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"ปรีชา  ยามวงศ์","fullname_en"=>"-","nickname"=>"V.ปรีชา (Max)","tel"=>"084-482 9990","line"=>"","license_no"=>"นข6090 ชร","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"ศราวุฒิ จันทร์อิน","fullname_en"=>"-","nickname"=>"V.เบิร์ด","tel"=>"063-789 9911","line"=>"","license_no"=>"36-0285 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"จีรวาวัฒน์  ยิ่งนิยม","fullname_en"=>"-","nickname"=>"V.ตุ่น","tel"=>"089-565 4391 , 083-766 1001","line"=>"","license_no"=>"นค2727 ชม","note"=>"บริการดี ขับรถดี  ปกติทำทัวร์ไทย  มีบัตรผ่านกองบิน","seat"=>"9","is_provincial"=>"1","is_wing41"=>"1","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"จรัส  ตันไชย","fullname_en"=>"-","nickname"=>"V.ตี๋ (Toon)","tel"=>"081-998 5772","line"=>"","license_no"=>"นง5354 ชม","note"=>"บริการดี ขับรถดี  ปกติทำทัวร์ไทย  มีบัตรผ่านกองบิน","seat"=>"9","is_provincial"=>"1","is_wing41"=>"1","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"พิษณุ  รอดนิยม","fullname_en"=>"-","nickname"=>"V.นุ (Toon)","tel"=>"087-192 5335","line"=>"","license_no"=>"36-0114 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"วิกร  แซ่โง้ว","fullname_en"=>"-","nickname"=>"V.มด (Toon)","tel"=>"086-185 6565","line"=>"","license_no"=>"นก4444 ลป","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"พรนพดล  คำภีระ","fullname_en"=>"-","nickname"=>"V.โหละ หรือ นพ (Toon)","tel"=>"086-912 0827","line"=>"","license_no"=>"นง3434 ชม","note"=>"รับงานได้ไม่เกี่ยง  บ้านอยู่สารภี","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"อภิธนวัฒน์  ปวนยอด","fullname_en"=>"-","nickname"=>"V.ถม (Toon)","tel"=>"089-835 0121","line"=>"","license_no"=>"30-3746 ชม","note"=>"บริการดี  ขับรถดี  ปกติทำทัวร์ไทย  แต่ทำทัวร์ฝรั่งได้","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"สมศักดิ์  จักร์คำ","fullname_en"=>"-","nickname"=>"V.หล้า (Toon)","tel"=>"093-213 6892","line"=>"","license_no"=>"นง3668 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"ณรงค์  ครองมี","fullname_en"=>"-","nickname"=>"V.ณรงค์ (Toon)","tel"=>"087-185 4220","line"=>"","license_no"=>"36-0059 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"ประสงค์  ใหม่ปัน","fullname_en"=>"-","nickname"=>"V.ประสงค์ (Toon)","tel"=>"081-746 3851","line"=>"","license_no"=>"30-2367 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"สุพจน์","fullname_en"=>"-","nickname"=>"V.พจน์ (อาร์ม)","tel"=>"088-432 7204","line"=>"","license_no"=>"นง7645 ชม","note"=>"ไม่รับงานต่างจังหวัด","seat"=>"9","is_provincial"=>"0","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"4","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"ธีรศักดิ์  กล่อมสุนทร","fullname_en"=>"-","nickname"=>"V.อาร์ม","tel"=>"082-896 5585","line"=>"","license_no"=>"30-2440 ชม","note"=>"ไม่รับงานต่างจังหวัด","seat"=>"9","is_provincial"=>"0","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"4","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"สมชาติ  ตาใส","fullname_en"=>"-","nickname"=>"V.สมชาติ (Toon)","tel"=>"081-884 3890","line"=>"","license_no"=>"36-0119 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"4","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"สมบัติ  จักร์คำ","fullname_en"=>"-","nickname"=>"V.น้อง (Toon)","tel"=>"089-632 9900","line"=>"","license_no"=>"36-0018 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"4","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"วรพจน์  แก้วมา","fullname_en"=>"-","nickname"=>"V.แอ๊ด (Toon)","tel"=>"090-756 5866","line"=>"","license_no"=>"นง8904 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"4","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"คมฤทธิ์  สลักคำ","fullname_en"=>"-","nickname"=>"V.คม (Toon)","tel"=>"081-386 4674","line"=>"","license_no"=>"นค1444 ชม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"4","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"ธานินทร์  อินอ่อน","fullname_en"=>"-","nickname"=>"V.ต๋อย (โกอ้วน Max)","tel"=>"087-764 2314","line"=>"","license_no"=>"36-0151 ชม","note"=>"มีรถหลายคัน  ติดต่อจาก  V.Max","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"สุวิทย์  สมรภูมิ","fullname_en"=>"-","nickname"=>"V.ต้อม","tel"=>"085-707 7445","line"=>"","license_no"=>"36-0072 ชม , ฮจ5229 กทม","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
		driver::create(["fullname_th"=>"","fullname_en"=>"","nickname"=>"V.หล้า (รวมรถ)","tel"=>"089-953 6468","line"=>"","license_no"=>"","note"=>"","seat"=>"9","is_provincial"=>"1","is_wing41"=>"0","is_staff"=>"0","is_priority"=>"3","is_sticker"=>"0"]);
	}
}
?>