<?php

use App\guide as Guides;
use Illuminate\Database\Seeder;

class GuideSeeder extends Seeder{
	public function run(){
		Guides::truncate();
		Guides::create(["fullname_th"=>"วิญญาณ์  วิเศษรัตน์","fullname_en"=>"Winya Wisetrat","nickname"=>"Toh","tel"=>"081-950 5810","line"=>"","license_no"=>"21-00056","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"0","is_priority"=>"0"]);
		Guides::create(["fullname_th"=>"ทานตะวัน  ชัยวิจัตร","fullname_en"=>"Tantawan Chaiwichit","nickname"=>"Toi","tel"=>"080-070 6963","line"=>"","license_no"=>"41-03048","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"1","is_priority"=>"1"]);
		Guides::create(["fullname_th"=>"วิีรยุท  นิมิตธำรงกุล","fullname_en"=>"Wirachai Nimitthamrongkun","nickname"=>"Bee","tel"=>"095-271 0838","line"=>"","license_no"=>"21-11323","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"1","is_priority"=>"1"]);
		Guides::create(["fullname_th"=>"สุชัญญสินี  ตรีสุข","fullname_en"=>"Suchanyasinee Trisuk","nickname"=>"Chanya (Jum)","tel"=>"087-660 8929","line"=>"","license_no"=>"11-49628","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"1","is_priority"=>"1"]);
		Guides::create(["fullname_th"=>"ธวัชชัย  ยาสาร","fullname_en"=>"Tawatchai Yasan","nickname"=>"M","tel"=>"091-853 4415","line"=>"","license_no"=>"21-12193","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"1","is_priority"=>"1"]);
		Guides::create(["fullname_th"=>"มานิตย์  สุขวัฒน์","fullname_en"=>"Manit Sukavat","nickname"=>"Manit","tel"=>"081-961 1801","line"=>"","license_no"=>"21-00121","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"1","is_priority"=>"1"]);
		Guides::create(["fullname_th"=>"ศักดิ์ดา  คิงคำ","fullname_en"=>"Sakda Kingkam","nickname"=>"Tui","tel"=>"095-676 3396","line"=>"","license_no"=>"21-12195","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"1","is_priority"=>"1"]);
		Guides::create(["fullname_th"=>"จงจิต  พานิชกุล","fullname_en"=>"Jongjit Panichkul","nickname"=>"Audy","tel"=>"087-443 4222","line"=>"","license_no"=>"21-02172","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"อุษณีย์  จ่อเรือง","fullname_en"=>"Usanee Jaurueng","nickname"=>"Euang","tel"=>"089-023 0075","line"=>"","license_no"=>"21-04996","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"จิราพร  ต้นนาค","fullname_en"=>"Jiraporn Tonnark","nickname"=>"Jira","tel"=>"081-764 6220","line"=>"","license_no"=>"21-02262","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"พลากร  เจริญวัย","fullname_en"=>"Palakorn Chareonval","nickname"=>"Puala","tel"=>"083-579 9861","line"=>"","license_no"=>"21-03824","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"จารุเดช  จาแก้ว","fullname_en"=>"Charudet Chakeaw","nickname"=>"Tommy","tel"=>"081-288 6594","line"=>"","license_no"=>"23-00240","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"มุจลินทร์  ปัญญา","fullname_en"=>"Mutchalin Panya","nickname"=>"Weaw","tel"=>"086-913 0655","line"=>"","license_no"=>"21-01385","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"ยะวัน  ทุ่งพิศาลพฤกษ์","fullname_en"=>" Yawan Thungphisanphluek","nickname"=>"Yawan","tel"=>"089-023 0075","line"=>"","license_no"=>"21-07056","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"ธนู  มโนธรรม","fullname_en"=>"Thanu Manotham","nickname"=>"Whanu","tel"=>"081-882 4915","line"=>"","license_no"=>"21-00422","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"พจนารถ  เทพสาตรา","fullname_en"=>"Potjanart Thepsatra","nickname"=>"Tom (Poj)","tel"=>"084-613 4152","line"=>"","license_no"=>"21-08633","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"จิณณ์พิชญ์  ฉัตรสุวรรณ","fullname_en"=>"Jinpeed Chatsuwan","nickname"=>"Chacha","tel"=>"084-347 0666","line"=>"","license_no"=>"21-04142","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"จิราศักดิ์  อัตวุฒิ","fullname_en"=>"Chirasak Attawut","nickname"=>"Phant","tel"=>"084-490 1523","line"=>"","license_no"=>"21-12221","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"วริศรา  นะต๊ะ","fullname_en"=>"Warissara Nata","nickname"=>"Nong","tel"=>"081-885 2003","line"=>"","license_no"=>"21-05728","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"เนน์ตินัย  พระไตรยะ","fullname_en"=>"Netinai Phratriya","nickname"=>"NeNe","tel"=>"081-180 3443","line"=>"","license_no"=>"21-08515","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"รุ่งนภา  งามเมือง","fullname_en"=>"Roongnapa Ngammuang","nickname"=>"Rung","tel"=>"081-993 3216","line"=>"","license_no"=>"21-00561","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"เพียงทิพย์  จันทร์แดง","fullname_en"=>"Piangtip Chandang","nickname"=>"Tip","tel"=>"081-881 7349","line"=>"","license_no"=>"21-02953","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"นิรยุทธ  กิตติกุล","fullname_en"=>"Nirayut Kittikul","nickname"=>"เต้ย","tel"=>"095-687 3235","line"=>"","license_no"=>"21-11374","card_expired"=>"-","note"=>"ทำภาษาอังกฤษ และ ภาษาญี่ปุ่น","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"สญชัย  ทำบุญ","fullname_en"=>"Sonchai Thumboon","nickname"=>"Sonchai","tel"=>"081-724 6258","line"=>"","license_no"=>"21-01283","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"วัชราพร  คำนวล","fullname_en"=>"Watcharapon Khumnuan","nickname"=>"Noi","tel"=>"081-671 0173","line"=>"","license_no"=>"21-03277","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"วยุคนธ์  พื้นต๊ะศรี","fullname_en"=>"Wayukon Phuntasri","nickname"=>"Kik (Wayukon)","tel"=>"080-500 7870","line"=>"","license_no"=>"21-07088","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"ทิพากร  หวังพานิช","fullname_en"=>"Tipakorn Wangwanit","nickname"=>"Kung","tel"=>"081-952 9213","line"=>"","license_no"=>"21-01136","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"พรทิพย์  วิมลมาลย์","fullname_en"=>"Pontip Vimolmal","nickname"=>"Kae","tel"=>"089-225 3625","line"=>"","license_no"=>"23-01583","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"นิิตยา  กันธิยะ","fullname_en"=>"Nittaya Ganthiya","nickname"=>"Nity","tel"=>"081-882 5863","line"=>"","license_no"=>"21-00011","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"แสงจันทร์  มณีธร","fullname_en"=>"Sangchan Maneetorn","nickname"=>"JJ","tel"=>"085-041 6813","line"=>"","license_no"=>"23-05895","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"ภูษณิศา  กันทวงค์","fullname_en"=>"Pusanisa Kantavong","nickname"=>"Mons","tel"=>"061-294 6364","line"=>"","license_no"=>"21-05916","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"เกรียงไกร  ปันตะทา","fullname_en"=>"Kriengkrai Punthata","nickname"=>"Noom","tel"=>"086-184 3222","line"=>"","license_no"=>"23-00941","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"ณัฐชานันท์  ชมภูเทศ","fullname_en"=>"Natchanun Chompooted","nickname"=>"Su","tel"=>"081-881 6724","line"=>"","license_no"=>"21-02837","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"มนตรี  แสงพิชัย","fullname_en"=>"Montree Saengpichai","nickname"=>"Tri","tel"=>"089-755 4465","line"=>"","license_no"=>"23-00938","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"-","fullname_en"=>"-","nickname"=>"ToiTing","tel"=>"097-924 9559","line"=>"","license_no"=>"-","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"2"]);
		Guides::create(["fullname_th"=>"รัชภูมิ  สุภาวรรณ","fullname_en"=>"Ratchapoom Supawan","nickname"=>"Richcy","tel"=>"089-263 5288","line"=>"","license_no"=>"21-04820","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"3"]);
		Guides::create(["fullname_th"=>"พัชรีพร  กิวัฒนา","fullname_en"=>"Patchareeporn Giwattana","nickname"=>"Moo","tel"=>"097-260 8907","line"=>"","license_no"=>"21-02118","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"3"]);
		Guides::create(["fullname_th"=>"ทักษอร  แสงมีอานุภาพ","fullname_en"=>"Thaksaorn Seangmi-anuphab","nickname"=>"Por","tel"=>"085-705 7928","line"=>"","license_no"=>"21-04858","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"3"]);
		Guides::create(["fullname_th"=>"แสงทอง  อินวาลิน","fullname_en"=>"Sagthong Ainwalin","nickname"=>"Pu","tel"=>"081-993 5925","line"=>"","license_no"=>"21-02043","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"3"]);
		Guides::create(["fullname_th"=>"มนทิรา  วิละชาญ","fullname_en"=>"Montira Wilachan","nickname"=>"Mona","tel"=>"087-724 9451","line"=>"","license_no"=>"21-02885","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"3"]);
		Guides::create(["fullname_th"=>"แจ่มนภา  สมการ","fullname_en"=>"Jamnapa Somkarn","nickname"=>"Ae (Jam)","tel"=>"086-186 4277","line"=>"","license_no"=>"21-01945","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"3"]);
		Guides::create(["fullname_th"=>"มนตรี  ลบแย้ม","fullname_en"=>"Montri Lobyaem","nickname"=>"Keng","tel"=>"089-553 4422","line"=>"","license_no"=>"21-08483","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"3"]);
		Guides::create(["fullname_th"=>"ธีรวัฒน์  วงษ์สุริยะ","fullname_en"=>"Theerawat Wongsuriya","nickname"=>"Boy","tel"=>"095-271 0838","line"=>"","license_no"=>"21-08303","card_expired"=>"-","note"=>"","is_provincial"=>"1","is_staff"=>"2","is_priority"=>"3"]);		
	}
}
?>