<?php

use App\hotel as hotel;
use Illuminate\Database\Seeder;

class HotelSeeder extends Seeder{
	public function run(){
		hotel::truncate();
		hotel::create(["hotel"=>"137 Pillars House","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Akyra Manor","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Amata Lanna","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Amora Thapae","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Anoma Boutique","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Anantara Chiang Mai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Art Mai Gallery Nimman","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Aruntara","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"At Chiang Mai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"At Nimman","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"At Ping Nakorn (Nimmanhaemin Rd.)","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"At Ping Nakorn (Huay Kaew Rd.)","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"B2 Ayatana","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"B House Boutique","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Baan Boo Loo","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Baan Huen Phen","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Baan Klang Wieng","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Baan Ratchiangsean","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Baan Saen Fang","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Baan Thai Village","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Baan U Sabai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Ban Chang Tong","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Baiyoke Ciao","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"BB Montra","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Bed Chankian","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Bed Phrasingh","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Big Tree Boutique","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Bodhi Serene","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Burisiri Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Casa 2511","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Chang Thai House","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Chanett Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Chiang Mai Boutique","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Chiang Mai Gate","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Chiang Mai Orchid","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Chiang Mai Plaza","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Chompor Lanna","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Cmor Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Cozytel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Duangtawan Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Dusit D2","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Dusit Princess","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"De Chai Colonial (Nimman)","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"De Chai Colonial (Tha Pae)","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"De Naga","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"99 Gallery&De Viang","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Eastin Tan Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Empire Residence","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Estia Boutique","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Eurana Boutique Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Furama Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"G2 Boutique","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"G’Morning Tropical","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Golden Wells","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Golden Bell Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Gord Chiang Mai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Green Nimman CMU Residence","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Green Tiger Vegetarian","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Holiday Inn Chiang Mai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Hotel Des Artists Ping Silhouette","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Hug Nimman Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Hyde Park Chiang Mai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Ibis Style Chiang Mai Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Imm Tha Pae","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Imperial Mae Ping","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"iWualai Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Jasmine Chiang Mai Boutique","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Jira Luxury","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Kampang Ngam","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Kantary Hills","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Kate & Hasu Boutique Chiang mai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Ketawa","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Kiree Thara","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Kodchasri Thani","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"La Pillow","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Lamphu House","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Lani Chiang Mai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Lanna Dusita Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Le Meridien Chiang Mai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"LeeChiang Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Lotus Pang Suan Kaew","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Makka","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Maraya Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"May Flower Grand Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Mercure","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"MD Boutique","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Mo Rooms","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Nap in Chiang Mai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Napatra Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Nam Ton Boutique","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Nawa Sheeva","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Nidhra Lanna","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Nimman Mai? Design Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Nimman Soi 9","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Nordwind","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Pak Chiang Mai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Pat’s Klang Viang","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Parasol Inn","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Patara Place","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Ping Nakara Boutique Hotel and Spa","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Pingpanakorn","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Pornping","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Portico 21 (P21)","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Prestige CM","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Puripunn Baby Grand Boutique","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Rachamankha","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Rachamanka Flora House","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Rarin Jinda Wellness Spa","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Ratchiangsean Flora House","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"RatiLanna Riverside Resort","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Rich Lanna House","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Rimping Village","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Rom Po","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Ruen Come Inn","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"S17 @ Nimman","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"S Private House","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Sala Lanna","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Seven Senses","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Shangri-La Chiang Mai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Shewe Wana","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Shiek Istana","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Singha Montra","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Sirilanna","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Siripanna Villa Resort & Spa","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Sireeampan","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Studio 9W","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Suriwongse Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"TadKham Village","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Tamarind Village","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Thannatee Boutique Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Tha Pae Loft","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Tri Yaan Na Ros","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"The 20 Lodge","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"The An-Teak Chiang Mai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"The Artel Niman","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"The Balcony","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"The Bed Nimman","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"The Grand Naphat","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"The Imperial Mae Ping Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"The Log Home","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"The Peaberry","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"The Rim Resort","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"The Sila Boutique","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"The Small","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"The Volcano","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"U Chaing Mai","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"U Nimman","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Vanilla Residence","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"VC @ Suan Pak","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Victoria Nimman","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Vieng Mantra","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Viang Tha Pae","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Villa Duang Champa","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Villa Tha Pae","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Wiang Chang Klan","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"We Run Boutique Hometel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"We Valley Boutique Hotel","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Western House","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Woodfield Resort","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Yaang Come Village","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Yantarasri Resort","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Yesterday","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"X2 Vibe Chiang Mai Decem","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Zzziesta","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
		hotel::create(["hotel"=>"Other","address"=>"","email"=>"","phone"=>"","fax"=>"","is_partner"=>"","is_obscure"=>""]);
	}
}
?>