<?php

use App\nationality as nationality;
use Illuminate\Database\Seeder;

class NationalitySeeder extends Seeder{
	public function run(){
		nationality::truncate();
		nationality::create(["nationality"=>"Afghan","country"=>"Afghanistan"]);
		nationality::create(["nationality"=>"Albanian","country"=>"Albania"]);
		nationality::create(["nationality"=>"Algerian","country"=>"Algeria"]);
		nationality::create(["nationality"=>"Andorran","country"=>"Andorra"]);
		nationality::create(["nationality"=>"Angolan","country"=>"Angola"]);
		nationality::create(["nationality"=>"Argentinian","country"=>"Argentina"]);
		nationality::create(["nationality"=>"Armenian","country"=>"Armenia"]);
		nationality::create(["nationality"=>"Australian","country"=>"Australia"]);
		nationality::create(["nationality"=>"Austrian","country"=>"Austria"]);
		nationality::create(["nationality"=>"Azerbaijani","country"=>"Azerbaijan"]);
		nationality::create(["nationality"=>"Bahamian","country"=>"Bahamas"]);
		nationality::create(["nationality"=>"Bahraini","country"=>"Bahrain"]);
		nationality::create(["nationality"=>"Bangladeshi","country"=>"Bangladesh"]);
		nationality::create(["nationality"=>"Barbadian","country"=>"Barbados"]);
		nationality::create(["nationality"=>"Belarusian or Belarusan","country"=>"Belarus"]);
		nationality::create(["nationality"=>"Belgian","country"=>"Belgium"]);
		nationality::create(["nationality"=>"Belizean","country"=>"Belize"]);
		nationality::create(["nationality"=>"Beninese","country"=>"Benin"]);
		nationality::create(["nationality"=>"Bhutanese","country"=>"Bhutan"]);
		nationality::create(["nationality"=>"Bolivian","country"=>"Bolivia"]);
		nationality::create(["nationality"=>"Bosnian","country"=>"Bosnia-Herzegovina"]);
		nationality::create(["nationality"=>"Botswanan","country"=>"Botswana"]);
		nationality::create(["nationality"=>"Brazilian","country"=>"Brazil"]);
		nationality::create(["nationality"=>"British","country"=>"Britain"]);
		nationality::create(["nationality"=>"Bruneian","country"=>"Brunei"]);
		nationality::create(["nationality"=>"Bulgarian","country"=>"Bulgaria"]);
		nationality::create(["nationality"=>"Burkinese","country"=>"Burkina"]);
		nationality::create(["nationality"=>"Burmese","country"=>"Burma"]);
		nationality::create(["nationality"=>"Burundian","country"=>"Burundi"]);
		nationality::create(["nationality"=>"Cambodian","country"=>"Cambodia"]);
		nationality::create(["nationality"=>"Cameroonian","country"=>"Cameroon"]);
		nationality::create(["nationality"=>"Canadian","country"=>"Canada"]);
		nationality::create(["nationality"=>"Cape Verdean","country"=>"Cape Verde Islands"]);
		nationality::create(["nationality"=>"Chadian","country"=>"Chad"]);
		nationality::create(["nationality"=>"Chilean","country"=>"Chile"]);
		nationality::create(["nationality"=>"Chinese","country"=>"China"]);
		nationality::create(["nationality"=>"Colombian","country"=>"Colombia"]);
		nationality::create(["nationality"=>"Congolese","country"=>"Congo"]);
		nationality::create(["nationality"=>"Costa Rican","country"=>"Costa Rica"]);
		nationality::create(["nationality"=>"Croat or Croatian","country"=>"Croatia"]);
		nationality::create(["nationality"=>"Cuban","country"=>"Cuba"]);
		nationality::create(["nationality"=>"Cypriot","country"=>"Cyprus"]);
		nationality::create(["nationality"=>"Czech","country"=>"Czech Republic"]);
		nationality::create(["nationality"=>"Danish","country"=>"Denmark"]);
		nationality::create(["nationality"=>"Djiboutian","country"=>"Djibouti"]);
		nationality::create(["nationality"=>"Dominican","country"=>"Dominica"]);
		nationality::create(["nationality"=>"Dominican","country"=>"Dominican Republic"]);
		nationality::create(["nationality"=>"Ecuadorean","country"=>"Ecuador"]);
		nationality::create(["nationality"=>"Egyptian","country"=>"Egypt"]);
		nationality::create(["nationality"=>"Salvadorean","country"=>"El Salvador"]);
		nationality::create(["nationality"=>"English","country"=>"England"]);
		nationality::create(["nationality"=>"Eritrean","country"=>"Eritrea"]);
		nationality::create(["nationality"=>"Estonian","country"=>"Estonia"]);
		nationality::create(["nationality"=>"Ethiopian","country"=>"Ethiopia"]);
		nationality::create(["nationality"=>"Fijian","country"=>"Fiji"]);
		nationality::create(["nationality"=>"Finnish","country"=>"Finland"]);
		nationality::create(["nationality"=>"French","country"=>"France"]);
		nationality::create(["nationality"=>"Gabonese","country"=>"Gabon"]);
		nationality::create(["nationality"=>"Gambian","country"=>"Gambia, the"]);
		nationality::create(["nationality"=>"Georgian","country"=>"Georgia"]);
		nationality::create(["nationality"=>"German","country"=>"Germany"]);
		nationality::create(["nationality"=>"Ghanaian","country"=>"Ghana"]);
		nationality::create(["nationality"=>"Greek","country"=>"Greece"]);
		nationality::create(["nationality"=>"Grenadian","country"=>"Grenada"]);
		nationality::create(["nationality"=>"Guatemalan","country"=>"Guatemala"]);
		nationality::create(["nationality"=>"Guinean","country"=>"Guinea"]);
		nationality::create(["nationality"=>"Guyanese","country"=>"Guyana"]);
		nationality::create(["nationality"=>"Haitian","country"=>"Haiti"]);
		nationality::create(["nationality"=>"Dutch","country"=>"Holland"]);
		nationality::create(["nationality"=>"Honduran","country"=>"Honduras"]);
		nationality::create(["nationality"=>"Hungarian","country"=>"Hungary"]);
		nationality::create(["nationality"=>"Icelandic","country"=>"Iceland"]);
		nationality::create(["nationality"=>"Indian","country"=>"India"]);
		nationality::create(["nationality"=>"Indonesian","country"=>"Indonesia"]);
		nationality::create(["nationality"=>"Iranian","country"=>"Iran"]);
		nationality::create(["nationality"=>"Iraqi","country"=>"Iraq"]);
		nationality::create(["nationality"=>"Irish","country"=>"Ireland, Republic of"]);
		nationality::create(["nationality"=>"Italian","country"=>"Italy"]);
		nationality::create(["nationality"=>"Jamaican","country"=>"Jamaica"]);
		nationality::create(["nationality"=>"Japanese","country"=>"Japan"]);
		nationality::create(["nationality"=>"Jordanian","country"=>"Jordan"]);
		nationality::create(["nationality"=>"Kazakh","country"=>"Kazakhstan"]);
		nationality::create(["nationality"=>"Kenyan","country"=>"Kenya"]);
		nationality::create(["nationality"=>"Kuwaiti","country"=>"Kuwait"]);
		nationality::create(["nationality"=>"Laotian","country"=>"Laos"]);
		nationality::create(["nationality"=>"Latvian","country"=>"Latvia"]);
		nationality::create(["nationality"=>"Lebanese","country"=>"Lebanon"]);
		nationality::create(["nationality"=>"Liberian","country"=>"Liberia"]);
		nationality::create(["nationality"=>"Libyan","country"=>"Libya"]);
		nationality::create(["nationality"=>"Lithuanian","country"=>"Lithuania"]);
		nationality::create(["nationality"=>"Macedonian","country"=>"Macedonia"]);
		nationality::create(["nationality"=>"Malagasy or Madagascan","country"=>"Madagascar"]);
		nationality::create(["nationality"=>"Malawian","country"=>"Malawi"]);
		nationality::create(["nationality"=>"Malaysian","country"=>"Malaysia"]);
		nationality::create(["nationality"=>"Maldivian","country"=>"Maldives"]);
		nationality::create(["nationality"=>"Malian","country"=>"Mali"]);
		nationality::create(["nationality"=>"Maltese","country"=>"Malta"]);
		nationality::create(["nationality"=>"Mauritanian","country"=>"Mauritania"]);
		nationality::create(["nationality"=>"Mauritian","country"=>"Mauritius"]);
		nationality::create(["nationality"=>"Mexican","country"=>"Mexico"]);
		nationality::create(["nationality"=>"Moldovan","country"=>"Moldova"]);
		nationality::create(["nationality"=>"Monégasque or Monacan","country"=>"Monaco"]);
		nationality::create(["nationality"=>"Mongolian","country"=>"Mongolia"]);
		nationality::create(["nationality"=>"Montenegrin","country"=>"Montenegro"]);
		nationality::create(["nationality"=>"Moroccan","country"=>"Morocco"]);
		nationality::create(["nationality"=>"Mozambican","country"=>"Mozambique"]);
		nationality::create(["nationality"=>"Namibian","country"=>"Namibia"]);
		nationality::create(["nationality"=>"Nepalese","country"=>"Nepal"]);
		nationality::create(["nationality"=>"Dutch","country"=>"Netherlands"]);
		nationality::create(["nationality"=>"New Zealand","country"=>"New Zealand"]);
		nationality::create(["nationality"=>"Nicaraguan","country"=>"Nicaragua"]);
		nationality::create(["nationality"=>"Nigerien","country"=>"Niger"]);
		nationality::create(["nationality"=>"Nigerian","country"=>"Nigeria"]);
		nationality::create(["nationality"=>"North Korean","country"=>"North Korea"]);
		nationality::create(["nationality"=>"Norwegian","country"=>"Norway"]);
		nationality::create(["nationality"=>"Omani","country"=>"Oman"]);
		nationality::create(["nationality"=>"Pakistani","country"=>"Pakistan"]);
		nationality::create(["nationality"=>"Panamanian","country"=>"Panama"]);
		nationality::create(["nationality"=>"Papua New Guinean or Guinean","country"=>"Papua New Guinea"]);
		nationality::create(["nationality"=>"Paraguayan","country"=>"Paraguay"]);
		nationality::create(["nationality"=>"Peruvian","country"=>"Peru"]);
		nationality::create(["nationality"=>"Philippine","country"=>"the Philippines"]);
		nationality::create(["nationality"=>"Polish","country"=>"Poland"]);
		nationality::create(["nationality"=>"Portuguese","country"=>"Portugal"]);
		nationality::create(["nationality"=>"Qatari","country"=>"Qatar"]);
		nationality::create(["nationality"=>"Romanian","country"=>"Romania"]);
		nationality::create(["nationality"=>"Russian","country"=>"Russia"]);
		nationality::create(["nationality"=>"Rwandan","country"=>"Rwanda"]);
		nationality::create(["nationality"=>"Saudi Arabian or Saudi","country"=>"Saudi Arabia"]);
		nationality::create(["nationality"=>"Scottish","country"=>"Scotland"]);
		nationality::create(["nationality"=>"Senegalese","country"=>"Senegal"]);
		nationality::create(["nationality"=>"Serb or Serbian","country"=>"Serbia"]);
		nationality::create(["nationality"=>"Seychellois","country"=>"Seychelles, the"]);
		nationality::create(["nationality"=>"Sierra Leonian","country"=>"Sierra Leone"]);
		nationality::create(["nationality"=>"Singaporean","country"=>"Singapore"]);
		nationality::create(["nationality"=>"Slovak","country"=>"Slovakia"]);
		nationality::create(["nationality"=>"Slovene or Slovenian","country"=>"Slovenia"]);
		nationality::create(["nationality"=>"Somali","country"=>"Somalia"]);
		nationality::create(["nationality"=>"South African","country"=>"South Africa"]);
		nationality::create(["nationality"=>"South Korean","country"=>"South Korea"]);
		nationality::create(["nationality"=>"Spanish","country"=>"Spain"]);
		nationality::create(["nationality"=>"Sri Lankan","country"=>"Sri Lanka"]);
		nationality::create(["nationality"=>"Sudanese","country"=>"Sudan"]);
		nationality::create(["nationality"=>"Surinamese","country"=>"Suriname"]);
		nationality::create(["nationality"=>"Swazi","country"=>"Swaziland"]);
		nationality::create(["nationality"=>"Swedish","country"=>"Sweden"]);
		nationality::create(["nationality"=>"Swiss","country"=>"Switzerland"]);
		nationality::create(["nationality"=>"Syrian","country"=>"Syria"]);
		nationality::create(["nationality"=>"Taiwanese","country"=>"Taiwan"]);
		nationality::create(["nationality"=>"Tajik or Tadjik","country"=>"Tajikistan"]);
		nationality::create(["nationality"=>"Tanzanian","country"=>"Tanzania"]);
		nationality::create(["nationality"=>"Thai","country"=>"Thailand"]);
		nationality::create(["nationality"=>"Togolese","country"=>"Togo"]);
		nationality::create(["nationality"=>"Trinidadian, Tobagan, Tobagonian","country"=>"Trinidad and Tobago"]);
		nationality::create(["nationality"=>"Tunisian","country"=>"Tunisia"]);
		nationality::create(["nationality"=>"Turkish","country"=>"Turkey"]);
		nationality::create(["nationality"=>"Turkmen or Turkoman","country"=>"Turkmenistan"]);
		nationality::create(["nationality"=>"Tuvaluan","country"=>"Tuvalu"]);
		nationality::create(["nationality"=>"Ugandan","country"=>"Uganda"]);
		nationality::create(["nationality"=>"Ukrainian","country"=>"Ukraine"]);
		nationality::create(["nationality"=>"UAE, Emirates, Emirati","country"=>"United Arab Emirates (UAE)"]);
		nationality::create(["nationality"=>"UK, British","country"=>"United Kingdom (UK)"]);
		nationality::create(["nationality"=>"US","country"=>"United States of America (USA)"]);
		nationality::create(["nationality"=>"Uruguayan","country"=>"Uruguay"]);
		nationality::create(["nationality"=>"Uzbek","country"=>"Uzbekistan"]);
		nationality::create(["nationality"=>"Vanuatuan","country"=>"Vanuatu"]);
		nationality::create(["nationality"=>"Venezuelan","country"=>"Venezuela"]);
		nationality::create(["nationality"=>"Vietnamese","country"=>"Vietnam"]);
		nationality::create(["nationality"=>"Welsh","country"=>"Wales"]);
		nationality::create(["nationality"=>"Western Samoan","country"=>"Western Samoa"]);
		nationality::create(["nationality"=>"Yemeni","country"=>"Yemen"]);
		nationality::create(["nationality"=>"Yugoslav","country"=>"Yugoslavia"]);
		nationality::create(["nationality"=>"Zaïrean","country"=>"Zaire"]);
		nationality::create(["nationality"=>"Zambian","country"=>"Zambia"]);
		nationality::create(["nationality"=>"Zimbabwean","country"=>"Zimbabwe"]);
		nationality::create(["nationality"=>"Other","country"=>"Other"]);
	}
}
?>