<?php

use App\tour_guide_fee_rate as TourGuideFeeRate;
use Illuminate\Database\Seeder;

class TourGuideFeeRateSeeder extends Seeder{
	public function run(){
		TourGuideFeeRate::truncate();
		TourGuideFeeRate::create(["tour_id"=>"1","tour_pax_id"=>"1","cost"=>"350","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"1","tour_pax_id"=>"2","cost"=>"400","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"1","tour_pax_id"=>"3","cost"=>"450","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"1","tour_pax_id"=>"4","cost"=>"500","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"2","tour_pax_id"=>"1","cost"=>"350","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"2","tour_pax_id"=>"2","cost"=>"400","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"2","tour_pax_id"=>"3","cost"=>"450","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"2","tour_pax_id"=>"4","cost"=>"500","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"3","tour_pax_id"=>"1","cost"=>"350","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"3","tour_pax_id"=>"2","cost"=>"400","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"3","tour_pax_id"=>"3","cost"=>"450","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"3","tour_pax_id"=>"4","cost"=>"500","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"4","tour_pax_id"=>"1","cost"=>"350","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"4","tour_pax_id"=>"2","cost"=>"400","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"4","tour_pax_id"=>"3","cost"=>"450","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"4","tour_pax_id"=>"4","cost"=>"500","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"5","tour_pax_id"=>"1","cost"=>"700","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"5","tour_pax_id"=>"2","cost"=>"800","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"5","tour_pax_id"=>"3","cost"=>"900","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"5","tour_pax_id"=>"4","cost"=>"1000","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"6","tour_pax_id"=>"1","cost"=>"350","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"6","tour_pax_id"=>"2","cost"=>"400","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"6","tour_pax_id"=>"3","cost"=>"450","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"6","tour_pax_id"=>"4","cost"=>"500","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"7","tour_pax_id"=>"1","cost"=>"400","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"7","tour_pax_id"=>"2","cost"=>"450","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"7","tour_pax_id"=>"3","cost"=>"500","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"7","tour_pax_id"=>"4","cost"=>"500","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"8","tour_pax_id"=>"1","cost"=>"700","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"8","tour_pax_id"=>"2","cost"=>"800","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"8","tour_pax_id"=>"3","cost"=>"900","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"8","tour_pax_id"=>"4","cost"=>"1000","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"9","tour_pax_id"=>"1","cost"=>"700","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"9","tour_pax_id"=>"2","cost"=>"800","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"9","tour_pax_id"=>"3","cost"=>"900","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"9","tour_pax_id"=>"4","cost"=>"1000","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"10","tour_pax_id"=>"1","cost"=>"1000","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"10","tour_pax_id"=>"2","cost"=>"1200","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"10","tour_pax_id"=>"3","cost"=>"1500","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"10","tour_pax_id"=>"4","cost"=>"1500","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"11","tour_pax_id"=>"1","cost"=>"700","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"11","tour_pax_id"=>"2","cost"=>"800","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"11","tour_pax_id"=>"3","cost"=>"900","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"11","tour_pax_id"=>"4","cost"=>"1000","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"12","tour_pax_id"=>"1","cost"=>"700","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"12","tour_pax_id"=>"2","cost"=>"800","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"12","tour_pax_id"=>"3","cost"=>"900","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"12","tour_pax_id"=>"4","cost"=>"1000","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"13","tour_pax_id"=>"1","cost"=>"700","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"13","tour_pax_id"=>"2","cost"=>"800","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"13","tour_pax_id"=>"3","cost"=>"900","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"13","tour_pax_id"=>"4","cost"=>"1000","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"14","tour_pax_id"=>"1","cost"=>"1000","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"14","tour_pax_id"=>"2","cost"=>"1200","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"14","tour_pax_id"=>"3","cost"=>"1500","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"14","tour_pax_id"=>"4","cost"=>"1500","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"15","tour_pax_id"=>"1","cost"=>"500","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"15","tour_pax_id"=>"2","cost"=>"600","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"15","tour_pax_id"=>"3","cost"=>"700","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"15","tour_pax_id"=>"4","cost"=>"700","is_famtrip"=>"1"]);
		TourGuideFeeRate::create(["tour_id"=>"16","tour_pax_id"=>"1","cost"=>"500","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"16","tour_pax_id"=>"2","cost"=>"600","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"16","tour_pax_id"=>"3","cost"=>"700","is_famtrip"=>"0"]);
		TourGuideFeeRate::create(["tour_id"=>"16","tour_pax_id"=>"4","cost"=>"700","is_famtrip"=>"1"]);
	}
}
?>